### ISSUE TITLE
Question about interpolated amplitude spectrum

### ISSUE THREAD

**Issue by zzzqzhou** [liuquande/FedDG-ELCFS#2]
Dear Quande, congratulations on your paper being accepted!
 I have a question about your paper. In the paper, you mentioned that you calculate the Interpolated Amplitude Spectrum by formular (2). From my perspecitve, I think the formular (2) means adding the central region of amplitude spectrum(AS) from the distribution bank multipling λ to the non-central region of AS from local image multipling (1-λ), which means the new AS's central region only contains the results calculated by AS from the distribution bank. However, in "freq_space_interpolation_demo.py" line 37, 
you just calculated the central region of new AS by adding the central region of original AS from local image to the central region of AS from the distribution bank(I left out λ for brevity), which I suppose does not match formular (2). 
Is this a mistake or did I misunderstand it？

**Comment by DopamineLcy** [comment]
I have the question as well. Maybe the (1-M) in formular (2) should be M, according to the codes, but maybe I misunderstood it.
Congratulations to authors and I hope for your reply.

**Comment by liuquande** [comment]
Dear all,

Thanks for the interest.

I think your understanding is right. 
The formular (2) should be corrected to A^{k-n} = _A^k*(1-M)_ + _(1-lambda) A^k * M + lambda * A^n * M_.

Thank you for pointing out this issue, I will update the arxiv version later.
  

Best.

**Comment by zzzqzhou** [comment]
Thanks for the clarification. Regards.

**Comment by DopamineLcy** [comment]
Thanks for your instantly reply. Regards.
