### ISSUE TITLE
It seems that some documents are absent?

### ISSUE THREAD

**Issue by lichen14** [liuquande/FedDG-ELCFS#4]
Dear author,
Thanks for your great work and released the project.
when I am rebuilding the FedDG, it seems that some documents are missing?

- https://github.com/liuquande/FedDG-ELCFS/blob/d59321cc72f09571a27777579d66b98c193631e0/train_ELCFS.py#L61
- https://github.com/liuquande/FedDG-ELCFS/blob/d59321cc72f09571a27777579d66b98c193631e0/train_ELCFS.py#L153

We sincerely hope to get your help. It would be great if you could answer our doubts or share related documents.

**Comment by liuquande** [comment]
Hi lichen,

Please refer to the latest reply at issue #3 .
