### ISSUE TITLE
Questions about data augmentation in fundus dataset.

### ISSUE THREAD

**Issue by BurningFr** [liuquande/FedDG-ELCFS#6]
Hi,
    In your released code, I cannot see the data augmentation operations in train_ELCFS.py which are introduced in your paper.  We can only see you use the ToTensor() operation, which is weird.

**Comment by liuquande** [comment]
Hi,

Thanks for the interest.

We performed the data augmentation offline and saved the augmented data as 'npy' format, in order to save the time cost for data loading and speed up the federated learning process.
